# dev_settings.yml
environment: dev

# Editable Values
city_council_date: 20250731 #format: YYYYMMDD
log_level_override: DEBUG

# Permenant Values
open_data_staging_path: data\GIS\BytesProduction
connection_file_path: connections\arcsdegis
primary_connection_file_name: sde@GISDEV.sde
trd_connection_file_name: sde@GISTRD.sde