# template_config.yml
environment: # dev or prod

# Editable Values
city_council_date: YYYYMMDD
log_level_override: # defaults to INFO when empty

# Permenant Values
local_staging_path: local repo dev data staging path
open_data_staging_path: primary open data output location path 
connection_file_path: path to SDE connection files
primary_connection_file_name: primary SDE name #format: sde@SDE_NAME.sde
trd_connection_file_name: secondary SDE name   #format: sde@SDE_NAME.sde